### ISSUE TITLE
How to apply `login_required`?

### ISSUE THREAD

**Issue by smmoosavi** [graphql-python/graphene-django#100]
Is there any better idea for check user is authenticated?
```python
urlpatterns += [
   url(r'^public-graphql', GraphQLView.as_view(graphiql=True, schema=public_schema)), 
   url(r'^user-graphql', login_required(GraphQLView.as_view(graphiql=True, schema=user_schema))),
]
```

**Comment by RadoRado** [comment]
I guess this can be helpful for you - http://docs.graphene-python.org/projects/django/en/latest/authorization/

Otherwise, since `GraphQLView` is a [class-based view](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L55), a better idea is to subclass it in your own view, adding the `LoginRequiredMixin` [from Django](https://docs.djangoproject.com/en/1.10/topics/auth/default/#the-loginrequired-mixin)

It would be something like that:

```python

class PrivateGraphQLView(LoginRequiredMixin, GraphQLView):
    pass

```

And then, you can use `PrivateGraphQLView.as_view()` in your urls.

This will do the trick.

Cheers! :beers:

**Comment by jahnagoldman** [comment]
When I try to use `LoginRequiredMixin` in this way and add the JWT to the request header it doesn't seem to recognize the user as authenticated. I believe I'm setting it up correctly and using an authenticated JWT because if I check in the schema `Query` class's `resolve_` method the user is authenticated, i.e.
```
def resolve_whoami(self, info):
        user = info.context.user
```

Does anyone know any reason why this might be? Does it require any other sort of configuration or different way of setting up your graphql request / header?

**Comment by thiras** [comment]
@jahnagoldman Would you be able to solve the problem? I'm struggling with the same problem.

**Comment by jahnagoldman** [comment]
> @jahnagoldman Would you be able to solve the problem? I'm struggling with the same problem.

Unfortunately I have not yet. I've just been using `login_required` at the function level since that does seem to work, though not very clean.

**Comment by mdilonne** [comment]
Did you guys win with subclassing LoginRequiredMixin?
