### ISSUE TITLE
Search filter in nested fields

### ISSUE THREAD

**Issue by Enorio** [graphql-python/graphene-django#1025]
I have two models, **ModelA** and **ModelB**. ModelB is a ManyToManyField in the ModelA.
And I'm trying to use the search filter in the nested fields that I request in the query. For example:

```
query {
  model_a(first: 10, search:"a") {
    edges {
      node {
        id
        related_model_b(search:"b") {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```
Since *model_a* and *model_b* have the two a schema.py and both have:
```
class Query(object):
    model_a = DjangoFilterConnectionField(ModelANode, search=graphene.String(), enforce_first_or_last=True)
class Query(object):
    model_b = DjangoFilterConnectionField(ModelBNode, search=graphene.String(), enforce_first_or_last=True)
```
Why do I get the error:
"Unknown argument \"search\" on field \"related_model_b\" of type \"ModelANode\"."

Is it because the related_model_b as a nested field is not an instance of DjangoFilterConnectionField?
But if I use **related_model_b(first:1)** the query works.

Any idea why this happens?

**Comment by houdabelefqih** [comment]
This is actually the expected behavior. Your **_related_model_b_** is an instance of **DjangoFilterConnectionField** (you can tell by the `edges { node { ... } } `syntax ) but it won't include your "_search_" argument for nested queries _UNLESS_ you specify it inside the parent node as an output field + define its resolver. It can look like something like this: 

``` python
class ModelANode(DjangoObjectType):
    related_model_b = DjangoFilterConnectionField(ModelBNode, search=graphene.String(), enforce_first_or_last=True)

    class Meta:
        interfaces = (relay.Node,)
        model = ModelA

    def resolve_related_model_b(self, info, **kwargs):
        # Get your search input from kwargs, filter you queryset as you wish then return
        search = kwargs.get('search')
        filtered_qs = self.related_model_b.filter(search=search)
        return filtered_qs 
```
So basically the queries you define in your ```class Query(object)``` are outer queries and if you want more control over their '**_children_**' you do that from within the **ModelNode**. I hope this makes sense 😅

PS: **first, last, before** and **after** are handled by default so you don't have to worry about them.
