### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by robd003** [graphql-python/graphene-django#1324]
It looks like there hasn't been a release in over a year and a half. Is there an active maintainer anymore?

**Comment by ulgens** [comment]
@robd003 It's dead. 

We talked many times about making one last release and announcing the project's EOL, but I wasn't able to do it. There are so many small things here and there that should be fixed and "the final release" turned out to be a pretty big responsibility. It may come in a week or a month, or may never happen, but even in case best case I don't think there will be a second one. So yes, it's basically dead.

**Comment by Djailla** [comment]
Do you advise any alternative ?

**Comment by pfcodes** [comment]
> @robd003 It's dead.
> 
> We talked many times about making one last release and announcing the project's EOL, but I wasn't able to do it. There are so many small things here and there that should be fixed and "the final release" turned out to be a pretty big responsibility. It may come in a week or a month, or may never happen, but even in best case I don't think there will be a second one. So yes, it's basically dead.

Sad. This was a great project.

**Comment by Byloth** [comment]
> Do you advise any alternative ?

@Djailla, I would suggest [Strawberry GraphQL](https://github.com/strawberry-graphql/strawberry) which also [supports Django](https://github.com/strawberry-graphql/strawberry-graphql-django) officially.  
The project appears to be healthy and thriving.

**Comment by chantezan** [comment]
is it very sad, but strawvery is actually active, check https://github.com/blb-ventures/strawberry-django-plus

**Comment by firaskafri** [comment]
> @tcleonard <img alt="hold up" width="300px" src="https://user-images.githubusercontent.com/877919/191308324-30f6b5b5-b224-4655-9b3e-c44a348df36f.png">
> 
> Bringing this back to life?

Yes hopefully :)
