### ISSUE TITLE
Please mark this project as dead!

### ISSUE THREAD

**Issue by jedie** [graphql-python/graphene-django#1334]
See: https://github.com/graphql-python/graphene-django/issues/1324#issuecomment-1140494403 this project is not active maintained. I think it should be clearly communicated e.g.: in README + github description.

**Comment by sanggi-wjg** [comment]
I agree . Also this project is not compatible with latest version.

**Comment by erikwrede** [comment]
We need some more time to get things sorted (See https://github.com/graphql-python/graphene-django/issues/1324#issuecomment-1161873284). 

I personally don't use graphene-Django, but many projects still rely on it and not everyone is able to switch  to another project. Urgent PRs will probably be merged if possible, but everything else depends on having someone onboard that has got enough time and sufficent knowledge of Django. 

Maybe a model where the community can approve something instead of maintainers would also work for some of the issues. But since the library has been practically dormant for quite long, trying that would be an experiment with unforeseeable outcome. But it might be worth to give it a shot, given the amount of users this library still has. But again, we need things sorted first before that can be decided. Will put up an honest note about the current state in the readme afterwards, just wanna be able to give clear directions on future procedures first.

As always, If anyone has any suggestions or thoughts on that, feel free to reply here or reach out on slack 🙂

**Comment by tasiotas** [comment]
what are the alternatives to django-graphene?

I only know of [Strawberry](https://strawberry.rocks/docs/integrations/django)

**Comment by tcleonard** [comment]
> I agree . Also this project is not compatible with latest version.

based on? the CI passes so I disagree (and I use it personally and it works just fine).

This project is not dead, indeed it is maintained. That being said it is dormant in the sense that new features are not being added very often.
But this is a public project, nobody is payed to work on it so new features come from the community. 
If you are missing features, instead of calling the project dead, submit a PR.
