### ISSUE TITLE
Check dependent libraries: https://github.com/tfoxy/graphene-django-optimizer and  https://github.com/eamigo86/graphene-django-extras

### ISSUE THREAD

**Issue by firaskafri** [graphql-python/graphene-django#1356]
Check dependent libraries: https://github.com/tfoxy/graphene-django-optimizer and  https://github.com/eamigo86/graphene-django-extras

**Comment by sjdemartini** [comment]
@firaskafri Thanks so much for your work to officially release v3.0.0 and revive this project! It turns out the v3.0.0 release unfortunately does not work with `graphene-django-optimizer` (though the v3.0.0b7 version _did_ work), since `graphene-django-optimizer` no longer properly optimizes queries when used with the non-beta version. I've opened a corresponding issue in that project https://github.com/tfoxy/graphene-django-optimizer/issues/86. 

I'm not familiar enough with the internals of `graphene-django-optimizer` or `graphene-django` to quickly identify what might have changed, but figured I'd post here as a heads up as well.

**Comment by sjdemartini** [comment]
@firaskafri Thanks again for all your work toward keeping this project alive. I saw you just released a new 3.0.1 version today! 🎉   I tried that version with `graphene-django-optimizer` like I did with 3.0.0, and (expectedly) it didn't fix the issue linked above with `graphene-django-optimizer`.  That package is critical for our team to be able to upgrade to `graphene-django` v3 and we'd love to be able to do so, as we're currently stuck on Django 3.2 due to using `graphene-django` 2.15.0. 

I investigated in more detail to see if I could help, and I came across the discussion here https://github.com/graphql-python/graphene-django/pull/1315#discussion_r1015659857. I tested reverting that change and indeed it did fix the query-optimization, so I've opened a PR to revert the problematic code https://github.com/graphql-python/graphene-django/pull/1401, which I believe is the right move at least until a more query-friendly approach could be implemented for it later. Thank you for considering, hopeful to upgrade and continue using `graphene-django`!

**Comment by sjdemartini** [comment]
graphene-django-optimizer support was fixed as of the above PR https://github.com/graphql-python/graphene-django/pull/1401 (published in 3.0.2), and graphene-django-extras added official graphene v3 support (non-beta) in its 1.0.0 version https://github.com/eamigo86/graphene-django-extras/pull/191, so closing this out! 🙌
