### ISSUE TITLE
This project uses reserved keywords

### ISSUE THREAD

**Issue by allen-munsch** [graphql-python/graphene-django#1386]
Sorry if this a duplicate, but I tried linting the project, and there are many uses of reserved keywords within the project see: `input` as one example

https://github.com/graphql-python/graphene-django/search?q=get_serializer_kwargs&type=code

**Comment by sjdemartini** [comment]
This project inherits the patterns from the more general `graphene` project, upon which it builds additional functionality for Django use-cases. For instance, usage of `input` in `graphene` [here](https://github.com/graphql-python/graphene/blob/03cf2e131e655402ccc0a9e2d9897c39d7f7f86a/graphene/relay/mutation.py#L55-L66). If there is a bug caused by shadowing of the python built-ins, feel free to file a new bug report with detailed steps to reproduce the bug, but I don't believe this causes any problems to downstream users of `graphene-django`.
