### ISSUE TITLE
Reusable apps/modules

### ISSUE THREAD

**Issue by morgante** [graphql-python/graphene-django#14]
One of the things which makes Django awesome is the ability to easily share apps across multiple projects. Django Rest Framework definitely leverages this by making it possible to include entire routes in your urls.py file (to reuse REST routes from other apps) or extending serializers/views if you want to customize another app.

I'd like to start a conversation on what the best approach is to reusable Graphene schemas with Django.

In particular, I think we need to have clear examples of:
1. If I want to wholesale include a reusable schema (ex. a generic "users" schema) from another project, how do I add it to mine.
2. If I want to extend another project's schema (ex. extending the users schema and changing the mutation to make names immutable), how do I do that.
3. What are best practices for developing reusable graphql schemas with Graphene.

I'm happy to work on pull requests, examples, or documentation once we have a bit of a consensus.

**Comment by petertrotman** [comment]
You can have multiple schema - one per app - if you define each app `Query` as an `AbstractType`, and then in your main project schema you can import them and include each one in the 'master' `Query` class through multiple inheritance of all the app `Query` classes.

See the main example http://docs.graphene-python.org/projects/django/en/latest/tutorial.html

**Comment by conradev** [comment]
I share schemas across apps with the approach that @petertrotman suggests and it works great.

Extending schemas in order to share code on the other hand is not very easy. I had to do a lot of hacking in order to get it to work.

**Comment by nerdoc** [comment]
I'm trying to get this done in a project which is not only app-pluggable, but a real plugin project. Django apps with a graphene schema need to be integrated by inheriting the main Query from all the apps' Queries. This on the one hand is cumbersome, as you need to inherit from 20 schemas when you have 20 apps - but even this OTOH does not solve the problem when you use dynamic plugins. I want Django to discover plugins by setuptools' entry_points automatically, and include them in the setup. This works reasonably well, but I can't get the graphene schemas to work, because, "dynamic" inheriting is a bit of a hack.
My current approach was having a "GlobalQuery" in the main project, which fetches all the subapps' queries by a pyutilib plugin interface/entrypoint and stuffs that class into the own `bases` dict. This is not only ugly, but does not work, as I found out that this global Query which is given as parameter to `schema` like
```python
schema = graphene.Schema(query=GlobalQuery)
```
is not even **instantiated** - all the methods are called directly on the class, right?

Here's an example of my code in schema.py:
```python
class GlobalQuery(TestMainQuery, graphene.ObjectType):
    def __init__(self):
        plugin_queries = ExtensionPoint(IGraphQLQuery)  # a pyutilib ExtensionPoint
    
        bases = []
        for query in self.plugin_queries:
            query_class = query.get_query()
            if query_class not in self.__bases__:
                bases.append(query_class)
        
            # FIXME: does not really work: dynamically inherit from plugged in Queries
            GlobalQuery.__bases__= tuple(bases) + \
                                (PluginSpecQuery, graphene.ObjectType, object)

```
Maybe I am completely wrong and there is a much lighter approach. Anyway, this does not work, because `__init__` is never called.
Ideas?

**Comment by nerdoc** [comment]
Oh. I found a solution, much simpler, in case of you are interested. 

I defined a decorator for the queries in all apps:
```python
class graphql_subquery:
    """Class decorator to include a class in the global GraphQL query"""
    query_classes = []

    def __init__(self, cls):
        self.cls = cls
        graphql_subquery.query_classes.append(cls)

    def __call__(self):
        self.cls()
```
And then in the project's schema.py, collect the queries from the decorator class, and create the main `Query` class dynamically:
```python
bases = tuple(graphql_subquery.query_classes + [graphene.ObjectType, object])
for cls in bases:
    print("Including '{}' in global GraphQL Query...".format(cls.__name__))

Query = type('Query', bases, {})
```
This works perfectly here.

**Comment by nerdoc** [comment]
closed, because....? WONTFIX, WORKSFORME?
I'm just interested if Graphene could implement this?

**Comment by fkromer** [comment]
Isn't this also an issue when one needs auto-generated documentation of the GraphQL API of a standalone Django app via `python manage.py graphql_schema`? @nerdoc Does your solution address this?

**Comment by nerdoc** [comment]
I changed my syntax a few times to find the best way of implementing all graphene schemas automatically.
My project is named [GDAPS](https://gitlab.com/nerdocs/gdaps), look at the [gdaps.graphene](https://gitlab.com/nerdocs/gdaps/-/tree/master/gdaps/graphene) module. It's not yet stable (has no working tests) - but should do what it says.

It simply creates an interface `IGrapheneSchema` which plugins can inherit, and all these schemas will be included automatically in the main schema - which is included automatically.
I haven't tested it, (TBH I didn't ever know about `./manage.py graphql_schema`) - but as it imports all plugin's `schema.py` files and records all of their Schema classes (see [README](https://gitlab.com/nerdocs/gdaps/-/tree/master/gdaps/graphene) in gdaps.graphene)  is included into one main object as normal working schemas, you can do everything you want with it, including call the `graphql_schema` command.
Just add your Graphene URL to your root urls.py as documented.
