### ISSUE TITLE
Django filter on related objects no longer works

### ISSUE THREAD

**Issue by khankuan** [graphql-python/graphene-django#189]
Hi, the following test would fail:
```

def test_filter_filterset_related_field():
    class ArticleFilterNode(DjangoObjectType):

        class Meta:
            interfaces = (Node, )
            model = Article
            filter_fields = ['headline', 'reporter']

    class Query(ObjectType):
        all_articles = DjangoFilterConnectionField(ArticleFilterNode)

    r1 = Reporter.objects.create(first_name='r1', last_name='r1', email='r1@test.com')
    r2 = Reporter.objects.create(first_name='r2', last_name='r2', email='r2@test.com')
    Article.objects.create(headline='a1', pub_date=datetime.now(), reporter=r1, editor=r2)
    Article.objects.create(headline='a2', pub_date=datetime.now(), reporter=r2, editor=r1)

    query = '''
    query {
        allArticles(reporter: 1) {
            edges {
                node {
                    headline
                }
            }
        }
    }
    '''
    schema = Schema(query=Query)

    result = schema.execute(query)
    assert not result.errors
    # We should only get back a single article
    assert len(result.data['allArticles']['edges']) == 1
    assert result.data['allArticles']['edges']['node']['headline'] == 'a1'
```

`allArticles(reporter: 1)` returns empty results while `allArticles(headline: "a1")` and `allArticles` returned non-empty results. Has anyone used related fields for filtering? Cheers!

**Comment by jeffreybrowning** [comment]
Hi all.

It seems that the `id` here @khankuan is talking about is not the django model instance id, but instead the `global id` that Nodes in relay have by base64 encoding their type and django model id. That behavior works fine and the posted test runs when a correctly constructed global id is passed. 

However, this global id interface seems a little odd because if relay and graphql are separate entities, and graphql is agnostic as to what other tools are used to help it out, then relay-specific schema by default is out-of-scope -- even if relay and graphene are commonly used together.

This seems solvable with a non-global id filterset and field, which can live side-by-side with your global filtersets. The global filtersets should likely be part of a `relay_utils` folder or module, whereas the non-global id filterset is truly django specific and should probably be default behavior for a non-relay configuration of this project.

I am more than willing to write that myself if the y'all jive with that idea.
