### ISSUE TITLE
only_fields() not honored

### ISSUE THREAD

**Issue by oharlem** [graphql-python/graphene-django#250]
I have
```python
class ContentNode(DjangoObjectType):
    class Meta:
        model = Content
        only_fields = ('id', 'title')
        filter_fields = ['id', 'title']
```

In a schema:
```python
content_list = DjangoFilterConnectionField(ContentNode)
```

However, query 
```graphQL
{
  content_list(first: 1) {
    edges {
      node {
        id
        title
      }
    }
  }
  __debug {
    sql {
      raw_sql
    }
  }
}
```
will show that all table fields are being fetched, not just id & title.

THere's a workaround - a resolver with `.only('id', 'title')` will give the desired result, but from what I understand 'only_fields` should be enough.

Any help is appreciated!
D.

----
My requirements:

Django==1.10.4
git+https://github.com/graphql-python/graphene-django.git#egg=graphene-django
django-filter==1.0.4

**Comment by spockNinja** [comment]
At the moment, `only_fields` is only used to limit what shows in the schema and what can be returned in the graphql response. It is not being used on the ORM side of things.

This sounds like a reasonable assumption, however, and in cases of large text columns and such, could lead to a noticeable performance improvement.

I think the change would need to be made somewhere around [this section](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/fields.py#L77) of code to check for `only_fields` and call `iterable.only(*only_fields)`.

**Comment by dopeboy** [comment]
Agreed, this could have some positive performance benefits. I'm going to adjust the labels here to get some momentum going for a PR.

**Comment by jkimbo** [comment]
So after spending quite some time on trying to implement this I've come to the conclusion that always applying `.only` is not a good idea because it can actually make performance worse. For example if you have the following object type:

```python
class Person(DjangoObjectType):
	class Meta:
		model = PersonModel
		fields = ("age")

	name = String()

	def resolve_name(person, info):
		return f"{person.first_name} {person.last_name}"
```

In this example using `.only` would mean that Graphene would only fetch the `age` property of the model. However when a client requests `name` Django will have to go and fetch `first_name` and `last_name` resulting in 2 more queries than if we didn't try and automatically only fetch the necessary fields. This is worse for performance and quite surprising IMO.

I think the prefered way for developers to achieve performance improvements by only fetching fields that are used has to be on a case by case basis and is best done by overriding the `get_queryset` method on the `DjangoObjectType` class:

```python
class Person(DjangoObjectType):
	class Meta:
		model = PersonModel
		fields = ("age")

	name = String()

	def resolve_name(person, info):
		return f"{person.first_name} {person.last_name}"

	@classmethod
	def get_queryset(cls, queryset, info):
		return queryset.only('age', 'first_name', 'last_name')
```

Be warned that this will negate any benefits of using `prefetch_related` further up the resolve tree.

---

I'm going to close this issue now because I don't think there is anymore to do here.
