### ISSUE TITLE
Typo in convert function

### ISSUE THREAD

**Issue by 0xCMP** [graphql-python/graphene-django#251]
There is a typo in this function to convert postgres fields to a JSONString field.

https://github.com/graphql-python/graphene-django/blob/2929d0866c800ae6efa8d35bb40548940a70c31f/graphene_django/converter.py#L184

**Comment by dopeboy** [comment]
Thanks for the report @0xCMP. We're going to punt on this because the team has some bigger fish to fry but we may give it a second look down the line.

And in case it isn't clear, the typo doesn't break functionality because it is decorated by a higher order function - more details [here](https://docs.python.org/3/library/functools.html).
