### ISSUE TITLE
Graphen Django test client captures exceptions

### ISSUE THREAD

**Issue by DXist** [graphql-python/graphene-django#291]
Current behaviour: 

at the moment server side exception is logged and error message is returned as response in test client.

Expected behaviour:

exception should be propagated to test code making post mortem debugging possible.

**Comment by spockNinja** [comment]
Yes, the current behavior for the `GraphQLView` is to catch exceptions and return them as errors. Part of the reason for this, I believe, is to support `batch` graphql queries, and allow queries to succeed independent of each other.

If someone wanted to add this functionality, the places to target are in `views.py:GraphQLView:execute_graphql_request`. There are two generic `try/except` blocks in there where a "test" or "debug" flag could be checked to simply raise the error instead.

Alternatively, instead of your tests going through the `GraphQLView`, you can write your tests directly against your `Schema` as most of the tests in this repo do.
