### ISSUE TITLE
Unknown argument "description" on field "createEvent" of type "Query".

### ISSUE THREAD

**Issue by ADmitri42** [graphql-python/graphene-django#347]
Hi! When I create schema where one method has argument "description" getting error "Unknown argument", but if I'll using "descriptio" everything works very well
## doesn't work
`createEvent = graphene.Boolean(description=graphene.String())`
## work
`createEvent = graphene.Boolean(descriptio=graphene.String())`

**Comment by spockNinja** [comment]
I believe this is because `graphene.Boolean` inherits from `graphene.Field`, where `description` has a specific purpose, and will be pulled out of the arguments.

https://github.com/graphql-python/graphene/blob/master/graphene/types/field.py#L24

Is `createEvent` supposed to be a mutation? It would appear so. In which case, I believe you would want to do:

```
createEvent = CreateEventMutation.Field()
```

where `CreateEventMutation` is the mutation you have defined to handle `createEvent`.

See http://docs.graphene-python.org/en/latest/types/mutations/

Let me know if I'm understanding correctly, and if this solves your problem.

Thanks!
