### ISSUE TITLE
NonNull missing in conversions to DjangoListField

### ISSUE THREAD

**Issue by dperetti** [graphql-python/graphene-django#448]
I think `NonNull` should be enforced at two locations:
1) [Here](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/converter.py#L190), `required=True` should be added:
```python
 return DjangoListField(_type, required=True)
```
2) And [here](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/fields.py#L17), `NonNull()` should be added:
```python
 super(DjangoListField, self).__init__(List(NonNull(_type)), *args, **kwargs)
```
This is because:
1) When you retrieve the related Set of an object, you **never** get `None` : when no related items are returned, you get an empty Set.
2) You never, ever get a Set of `None`.

Current implementation causes issues when using third party tools that introspect the schema, like apollo-codegen. (One gets very annoying nested optionals of nested optionals that make no sense and require additional checking).

Hope that makes sense.
(I can do a PR)

**Comment by dperetti** [comment]
I beg to differ with the stale bot. This is highly important.

**Comment by jkimbo** [comment]
Sorry for the bot @dperetti - we're just trying to get through a very long backlog of issues and it's useful to remove irrelevant old issues and surface the ones that are still a problem (like this one!). I'll reopen this issue since your suggestions sound sensible. Do you think you'll be able to create a PR for this @dperetti ?

**Comment by dperetti** [comment]
Cool, I will !
