### ISSUE TITLE
NormalCursorWrapper has invalid sigatures for callproc and execute

### ISSUE THREAD

**Issue by kevingill1966** [graphql-python/graphene-django#586]
File: /debug/sql/tracking.py          

The callproc and execute methods have an incorrect signature. This is causing a substitution attempt in the standard code, which breaks if there are '%'s in the SQL function.

    def callproc(self, procname, params=()):
          return self._record(self.cursor.callproc, procname, params)
  
    def execute(self, sql, params=()):
          return self._record(self.cursor.execute, sql, params)

**Comment by pauricthelodger** [comment]
I'm afraid this bug is still present on master =(  The default params `()` in the two `NormalCursorWrapper` methods should be `None` to match what django expects in the code block below.

```
    def execute(self, sql, params=None):
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)
E               IndexError: tuple index out of range

django/db/backends/utils.py:65: IndexError
```

@kevingill1966 has the fix on his fork - https://github.com/kevingill1966/graphene-django/commit/0d7fac49c731859bac7688be19c40ffad84342c9
