### ISSUE TITLE
context.user is not picking up my currently loged in user

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#7]
I'm logged into my app and i'm making requests to graphene. 

When I look at context.user I'm getting back an unauthorized user with a blank id. 
Is there some middleware that I missing? Or is this a bug

**Comment by syrusakbary** [comment]
Context is the same Django request provided to the GraphQL view, so it seems the request that the GraphQL view is receiving doesn't have an authenticated user.
It could be because the session getter is not working properly or because of graphene.

In any case, a PR with a broken test reproducing this issue would help to see what's going on! :)

**Comment by BossGrand** [comment]
Will do!

**Comment by BossGrand** [comment]
Doing further digging this was caused because I was did not have

'credentials': 'same-origin',  in my Relay NetworkLayer

     environment.injectNetworkLayer(new HelloOfficeNetworkLayer('/graphql_csrf', {
         'credentials': 'same-origin',
          headers: {
              'X-CSRFToken': window.csrfmiddlewaretoken,
           },
     }));
