### ISSUE TITLE
Queries selecting too much data

### ISSUE THREAD

**Issue by themotu** [graphql-python/graphene-django#702]
A query like this:

```
{
  allTimeobjects (first:1) {
   edges {
    node {
      id,
      beginning,
      end,
      elapsed
    }
  }
  }
}
```

Executes the exact same SQL as this:
```
{
  allTimeobjects {
   edges {
    node {
      id,
      beginning,
      end,
      elapsed
    }
  }
  }
}
```

They also both select all columns and not **only** the ones we are asking for. (only tested on sqlite but assume postgresql would be the same behavior)

#402 related

**Comment by artofhuman** [comment]
Related https://github.com/graphql-python/graphene-django/issues/250

**Comment by jkimbo** [comment]
@themotu I'm a bit confused about your example. In both queries the same fields are requested so I would always expect the same SQL to be executed. Could you expand on what you mean?

**Comment by wolendranh** [comment]
I think what is meant here is that when you request 
```
query {
  allReviews {
    id
  }
}
```
and 
```
query {
  allReviews {
    id,
    name
  }
}
```
Django ORM will execute same query (`Review.objects.all()`)
Bu in first case it COULD be for example `Review.objects.values('id')` and in second ``Review.objects.values('id', 'name')``.

**Comment by OskarPersson** [comment]
@wolendranh Usually [`.only()`](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#only) is better suited for this.

Either way I'm not sure how this could automatically be integrated with graphene-django though since users manually write their queries in the resolvers. And even doing so seems to result in some weird behaviour according to my limited testing where there instead is one or more sql query per resulting object with each query selecting different fields.

**Comment by wolendranh** [comment]
@OskarPersson I get your point. But maybe something like https://github.com/tfoxy/graphene-django-optimizer can be incorporated. Taking into account that related #250

**Comment by jkimbo** [comment]
@OskarPersson @wolendranh I don’t like the idea of building into graphene-django something that always automatically selects only fields that are requested because I think it could actually lead to worse behaviour since Django can’t cache queries consistently. However I would recommend using something like graphene-django-optimiser on a case by case basis if it helps you.

Separately I think #250 is a very good idea and when I get time I’ll look into implementing it. 

Going to close this issue now in favour of tracking everything in #250
