### ISSUE TITLE
Integration with Neo4J Database

### ISSUE THREAD

**Issue by nrgx** [graphql-python/graphene-django#727]
This not an issue. It's more like question. I want my nodes being able serializable to and from GraphQL. I use neomodel as OGM hence graphene-django (DjangoObjectType class) doesn't recognize my nodes as valid Django models. Then I used graphene's ObjectType class and it doesn't raise errors on validity of my nodes, but it asks for `_meta` attribute, I provided it with class NodeMeta, which has only one attribute name with values "node". As it seems it tried to convert to GraphQL type, as error states `Can only create List of a GraphQLType but got: None.`

**Comment by jkimbo** [comment]
Hi @nrgx ,

So this has been raised before (https://github.com/graphql-python/graphene-django/issues/442) and I think the issue is that neomodel doesn't actually subclass `django.db.models.Model` so graphene-django doesn't recognise it. This is not that unexpected since graphene-django is specifically for use with Django models.

It might be that the solution here is create a graphene-neo4j library?

**Comment by nrgx** [comment]
Hello, @jkimbo . Thanks for the reply. Learning the source code gave understanding of incompatibility of 2 packages. So I forked `graphene-django` and making on top of it bindings with neomodel. But, it seems to me, that will take a long time. I've got no question and closing this issue.

**Comment by jkimbo** [comment]
Ok thanks @nrgx . Do feedback if you have any success!

**Comment by SewerynPiorkowski** [comment]
Hello. Almost two years have passed. Has anyone found a solution to the problem?

**Comment by luisroel91** [comment]
https://github.com/MardanovTimur/graphene-neo4j

But it's probably stale at this point. Two years old.
