### ISSUE TITLE
Request a mutation with invalid inputs return status code 200

### ISSUE THREAD

**Issue by no-dap** [graphql-python/graphene-django#804]
DjangoFormMutation and SerializerMutation return status code 200 even if inputs are invalid.  
I found a test code that asserts 200 is correct but isn't it should be 400 rather than 200?  
[graphene_django.tests.test_views.test_handles_field_errors_caught_by_graphql](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/tests/test_views.py#L447)

**Comment by no-dap** [comment]
<img width="1464" alt="Screen Shot 2019-10-19 at 12 20 49 PM" src="https://user-images.githubusercontent.com/26595506/67153489-595b3580-f325-11e9-8c3b-686f50f0e1b1.png">

**Comment by jkimbo** [comment]
@no-dap generally GraphQL HTTP servers don't return anything other than 200 HTTP status codes and any errors are passed back to the client through the "errors" field in the response object. This is mainly because GraphQL supports multiple operations in a single request so it's entirely possible that a request only partially fails and returns both data **and** errors. 

Going to close this issue because I don't think this behaviour should change.
